apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: alpha1
  labels:
    type: local
spec:
  storageClassName: document
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/alpha1"